site_name: PowerWamp
repo_url: https://github.com/jpsider/PowerWamp
theme: readthedocs
pages:
- Home: index.md
- PowerWamp Basics:
  - What is PowerWamp: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
